In [ ]:
#Load file as a pandas dataframe

from google.colab import files

uploaded = files.upload()

Saving A_II_Emotion_Data_Student_Copy_Final.xlsx to A_II_Emotion_Data_Student_Copy_Final.xlsx


In [ ]:
import pandas as pd
df = pd.read_excel('A_II_Emotion_Data_Student_Copy_Final.xlsx')
print(df.head())

      ID_ brand_name_ country_  star_rating_ emotions_  \
0     ID1          Z_       US             5       NaN   
1    ID10          Z_       GB             5       NaN   
2   ID100          H_      FRI             5       joy   
3  ID1000          H_       GB             1      fear   
4  ID1001          H_       GB             1       NaN   

                                       text_reviews_  
0  Fast shipping! All cloths was finally fits wel...  
1  Just wanted to say how delighted I was with th...  
2  My order took 6 days with a snow day and a wee...  
3  Wouldnt give them no stars. I ordered a coat 4...  
4  Parcel never arrived. Chasing for a refund for...  


In [ ]:
#Cleaning corrupted comments

# Use a regular expression to match rows that contain only English letters, digits, spaces, and selected punctuation
mask = df['text_reviews_'].str.match(r'^[A-Za-z0-9\s.,?!\'"-]*$')

# Apply the mask to filter the DataFrame
df = df[mask]

# Display the filtered DataFrame to verify that rows with non-English characters have been removed while keeping numerics
print(df)

         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5699   ID979          H_       GB             1       NaN   
5704   ID983          H_       US             1       NaN   
5709   ID988          H_       GB             1       NaN   
5711    ID99          H_       DE             5       joy   
5720   ID998          H_       GB             1       NaN   

                                          text_reviews_  
0     Fast shipping! All cloths was finally fits wel...  
2     My order took 6 days with a snow day and a wee...  
3     Wouldnt give them no stars. I ordered a coat 4...  
4     Parcel never arrived. Chasing

In [ ]:
#Removing HTML tags, punctuation, and special characters.
#Converting text to lowercase.

In [ ]:
import re
import string
import pandas as pd

def clean_text(text):
    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    # Remove punctuation and special characters
    text = ''.join([char for char in text if char not in string.punctuation])
    # Convert text to lowercase
    text = text.lower()
    return text

# Apply the cleaning function to each row
df['cleaned_reviews'] = df['text_reviews_'].apply(clean_text)

# Display the DataFrame to verify changes
print(df[['text_reviews_', 'cleaned_reviews']].head())


                                       text_reviews_  \
0  Fast shipping! All cloths was finally fits wel...   
2  My order took 6 days with a snow day and a wee...   
3  Wouldnt give them no stars. I ordered a coat 4...   
4  Parcel never arrived. Chasing for a refund for...   
5  Avoid ordering online! Ordered 12 days ago, Ev...   

                                     cleaned_reviews  
0  fast shipping all cloths was finally fits well...  
2  my order took 6 days with a snow day and a wee...  
3  wouldnt give them no stars i ordered a coat 4 ...  
4  parcel never arrived chasing for a refund for ...  
5  avoid ordering online ordered 12 days ago evri...  
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_    

In [ ]:
#Word Level Tokenization

import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
def tokenize_text(text):
    tokens = word_tokenize(text)
    return tokens
df['tokenized_reviews'] = df['cleaned_reviews'].apply(tokenize_text)

# Display the DataFrame to verify changes
print(df[['cleaned_reviews', 'tokenized_reviews']].head())


                                     cleaned_reviews  \
0  fast shipping all cloths was finally fits well...   
2  my order took 6 days with a snow day and a wee...   
3  wouldnt give them no stars i ordered a coat 4 ...   
4  parcel never arrived chasing for a refund for ...   
5  avoid ordering online ordered 12 days ago evri...   

                                   tokenized_reviews  
0  [fast, shipping, all, cloths, was, finally, fi...  
2  [my, order, took, 6, days, with, a, snow, day,...  
3  [wouldnt, give, them, no, stars, i, ordered, a...  
4  [parcel, never, arrived, chasing, for, a, refu...  
5  [avoid, ordering, online, ordered, 12, days, a...  
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_    

In [ ]:
#Stop Word Removal

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import nltk
from nltk.corpus import stopwords

nltk.download('punkt')
nltk.download('stopwords')

def remove_stopwords(tokens):
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word.lower() not in stop_words]
    filtered_text = ' '.join(filtered_tokens)
    return filtered_text

df['no_stopwords'] = df['tokenized_reviews'].apply(remove_stopwords)

print(df[['tokenized_reviews', 'no_stopwords']].head())


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


                                   tokenized_reviews  \
0  [fast, shipping, all, cloths, was, finally, fi...   
2  [my, order, took, 6, days, with, a, snow, day,...   
3  [wouldnt, give, them, no, stars, i, ordered, a...   
4  [parcel, never, arrived, chasing, for, a, refu...   
5  [avoid, ordering, online, ordered, 12, days, a...   

                                        no_stopwords  
0   fast shipping cloths finally fits well satisfied  
2  order took 6 days snow day weekend happy sweat...  
3  wouldnt give stars ordered coat 4 weeks ago re...  
4  parcel never arrived chasing refund substantia...  
5  avoid ordering online ordered 12 days ago evri...  
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_    

In [ ]:
#Stemming Words

from nltk.stem import PorterStemmer

def stem_text(text):

    stemmer = PorterStemmer()

    words = word_tokenize(text)


    stemmed_words = [stemmer.stem(word) for word in words]


    stemmed_text = ' '.join(stemmed_words)

    return stemmed_text

df['stemmed_text'] = df['no_stopwords'].apply(stem_text)

# Display the DataFrame to verify changes
print(df[['no_stopwords', 'stemmed_text']].head())


                                        no_stopwords  \
0   fast shipping cloths finally fits well satisfied   
2  order took 6 days snow day weekend happy sweat...   
3  wouldnt give stars ordered coat 4 weeks ago re...   
4  parcel never arrived chasing refund substantia...   
5  avoid ordering online ordered 12 days ago evri...   

                                        stemmed_text  
0             fast ship cloth final fit well satisfi  
2  order took 6 day snow day weekend happi sweate...  
3  wouldnt give star order coat 4 week ago receiv...  
4  parcel never arriv chase refund substanti amou...  
5  avoid order onlin order 12 day ago evri packag...  
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_    

In [ ]:
#Lemitization

import spacy

# Load the spaCy model
nlp = spacy.load("en_core_web_sm")

def lemmatize_text(text):
    # Create a spaCy document object
    doc = nlp(text)
    # Extract the lemmatized form of each word
    lemmatized_text = ' '.join([token.lemma_ for token in doc])
    return lemmatized_text

# Apply the lemmatize_text function to each row in the 'stemmed_text' column
df['lemmatized_text'] = df['stemmed_text'].apply(lemmatize_text)

# Display the DataFrame to verify changes
print(df[['stemmed_text', 'lemmatized_text']].head())

print(df)

                                        stemmed_text  \
0             fast ship cloth final fit well satisfi   
2  order took 6 day snow day weekend happi sweate...   
3  wouldnt give star order coat 4 week ago receiv...   
4  parcel never arriv chase refund substanti amou...   
5  avoid order onlin order 12 day ago evri packag...   

                                     lemmatized_text  
0             fast ship cloth final fit well satisfi  
2  order take 6 day snow day weekend happi sweate...  
3  would not give star order coat 4 week ago rece...  
4  parcel never arriv chase refund substanti amou...  
5  avoid order onlin order 12 day ago evri packag...  
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_    

In [ ]:
#Bag of Words

from sklearn.feature_extraction.text import CountVectorizer

print(df['lemmatized_text'])


0                  fast ship cloth final fit well satisfi
2       order take 6 day snow day weekend happi sweate...
3       would not give star order coat 4 week ago rece...
4       parcel never arriv chase refund substanti amou...
5       avoid order onlin order 12 day ago evri packag...
                              ...                        
5699    order onlin blame delay evri courier case let ...
5704                      terribl return polici never buy
5709    total mind blow aw custom servicesdo buy onlin...
5711    packet come weekim super satisfiedeveryth fit ...
5720    complain late deliveri horrend compnay review ...
Name: lemmatized_text, Length: 1443, dtype: object
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     

In [ ]:
# Initialize the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the 'lemmatized_text' data to a bag of words representation
X = vectorizer.fit_transform(df['lemmatized_text'])

# Get the feature names, which corresponds to the vocabulary
feature_names = vectorizer.get_feature_names_out()
print(feature_names)

['01' '010' '05' ... 'zutiefst' 'zuwenig' 'zwei']
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5699   ID979          H_       GB             1       NaN   
5704   ID983          H_       US             1       NaN   
5709   ID988          H_       GB             1       NaN   
5711    ID99          H_       DE             5       joy   
5720   ID998          H_       GB             1       NaN   

                                          text_reviews_  \
0     Fast shipping! All cloths was finally fits wel...   
2     My order took 6 days with a snow day and a wee...   
3     Wouldnt give them no stars. I orde

In [ ]:
# Convert the sparse matrix to a dense matrix
X_dense = X.toarray()
print(X_dense)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5699   ID979          H_       GB             1       NaN   
5704   ID983          H_       US             1       NaN   
5709   ID988          H_       GB             1       NaN   
5711    ID99          H_       DE             5       joy   
5720   ID998          H_       GB             1       NaN   

                                          text_reviews_  \
0     Fast shipping! All cloths was finally fits wel...   
2     My order took 6 days wi

In [ ]:
# Create a new DataFrame with the BoW features
bow_df = pd.DataFrame(X_dense, columns=feature_names)

# Display the new DataFrame with the bag of words representation
print(bow_df)


      01  010  05  0511still  06  10  100  1001  11  11th  ...  zufrieden  \
0      0    0   0          0   0   0    0     0   0     0  ...          0   
1      0    0   0          0   0   0    0     0   0     0  ...          0   
2      0    0   0          0   0   0    0     0   0     0  ...          0   
3      0    0   0          0   0   0    0     0   0     0  ...          0   
4      0    0   0          0   0   1    0     0   0     0  ...          0   
...   ..  ...  ..        ...  ..  ..  ...   ...  ..   ...  ...        ...   
1438   0    0   0          0   0   0    0     0   0     0  ...          0   
1439   0    0   0          0   0   0    0     0   0     0  ...          0   
1440   0    0   0          0   0   0    0     0   0     0  ...          0   
1441   0    0   0          0   0   0    0     0   0     0  ...          0   
1442   0    0   0          0   0   0    0     0   0     0  ...          0   

      zufriedenheit  zufriedenkann  zum  zur  zusammen  zustand  zutiefst  

In [ ]:
#Removing columns that have numeric names

# Filter out columns where the column name represents a numeric value
bow_df = bow_df.loc[:, ~bow_df.columns.str.isnumeric()]

bow_df = bow_df.loc[:, ~bow_df.columns.to_series().apply(lambda x: x.replace('.', '', 1).isdigit())]

# Display the DataFrame to verify that numeric columns have been removed
print(bow_df)


      0511still  11th  12th  13th  16order  16th  17th  18ththey  19th  1e  \
0             0     0     0     0        0     0     0         0     0   0   
1             0     0     0     0        0     0     0         0     0   0   
2             0     0     0     0        0     0     0         0     0   0   
3             0     0     0     0        0     0     0         0     0   0   
4             0     0     0     0        0     0     0         0     0   0   
...         ...   ...   ...   ...      ...   ...   ...       ...   ...  ..   
1438          0     0     0     0        0     0     0         0     0   0   
1439          0     0     0     0        0     0     0         0     0   0   
1440          0     0     0     0        0     0     0         0     0   0   
1441          0     0     0     0        0     0     0         0     0   0   
1442          0     0     0     0        0     0     0         0     0   0   

      ...  zufrieden  zufriedenheit  zufriedenkann  zum  zur  z

In [ ]:
#Removing columns that have names starting with numeric

bow_df = bow_df.loc[:, ~bow_df.columns.str.match(r'^\d+.*')]

print(bow_df)


      aan  aanbevelen  aanbie  aanbiedingen  aanbod  aandringen  aangegeven  \
0       0           0       0             0       0           0           0   
1       0           0       0             0       0           0           0   
2       0           0       0             0       0           0           0   
3       0           0       0             0       0           0           0   
4       0           0       0             0       0           0           0   
...   ...         ...     ...           ...     ...         ...         ...   
1438    0           0       0             0       0           0           0   
1439    0           0       0             0       0           0           0   
1440    0           0       0             0       0           0           0   
1441    0           0       0             0       0           0           0   
1442    0           0       0             0       0           0           0   

      aangehouden  aangekoman  aangekomen  ...  zuf

In [ ]:
#Keeping only columns with column names present in the english dictionary

nltk.download('words')

# Load the set of English words from NLTK
from nltk.corpus import words
english_words = set(words.words())

# Filter columns based on whether their names are in the English words set
bow_df = bow_df.loc[:, bow_df.columns.isin(english_words)]

# Display the DataFrame to verify that non-English word columns have been removed
print(bow_df)


[nltk_data] Downloading package words to /root/nltk_data...
[nltk_data]   Package words is already up-to-date!


      abroad  absent  absurd  abysm  accept  access  accident  accord  \
0          0       0       0      0       0       0         0       0   
1          0       0       0      0       0       0         0       0   
2          0       0       0      0       0       0         0       0   
3          0       0       0      0       0       0         0       0   
4          0       0       0      0       0       0         0       0   
...      ...     ...     ...    ...     ...     ...       ...     ...   
1438       0       0       0      0       0       0         0       0   
1439       0       0       0      0       0       0         0       0   
1440       0       0       0      0       0       0         0       0   
1441       0       0       0      0       0       0         0       0   
1442       0       0       0      0       0       0         0       0   

      account  across  ...  york  young  your  yr  zag  zat  zero  zip  zo  \
0           0       0  ...     0      0     0

In [ ]:
#Word Cloud

# Calculate the sum of each column to get the count of occurrences
word_counts = bow_df.sum()

# Create a DataFrame with words and their occurrences
word_occurrences = pd.DataFrame({
    'Word': word_counts.index,
    'Occurrences': word_counts.values
})

# Sort the DataFrame by occurrences in descending order
word_occurrences_sorted = word_occurrences.sort_values(by='Occurrences', ascending=False)

# Reset the index for a clean table
word_occurrences_sorted.reset_index(drop=True, inplace=True)

# Display the DataFrame
print(word_occurrences_sorted)


            Word  Occurrences
0          order          404
1         custom          301
2           good          275
3          cloth          234
4            not          231
...          ...          ...
1507       major            1
1508        male            1
1509        malo            1
1510  manageress            1
1511        zoon            1

[1512 rows x 2 columns]
         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5699   ID979          H_       GB             1       NaN   
5704   ID983          H_       US             1       NaN   
5709   ID988          H_       GB             1       NaN   
5711 

In [ ]:
#Sentiment Analysis

from textblob import TextBlob

def analyze_sentiment(text):
    blob = TextBlob(text)  # Create a TextBlob object
    polarity = blob.sentiment.polarity  # Get the polarity score
    if polarity > 0:
        sentiment = "Positive"
    elif polarity < 0:
        sentiment = "Negative"
    else:
        sentiment = "Neutral"
    return sentiment, polarity

# Apply the analyze_sentiment function to each review in the DataFrame
df['Sentiment'], df['Polarity'] = zip(*df['text_reviews_'].apply(analyze_sentiment))

# Display the DataFrame to verify the sentiment and polarity columns
print(df)


         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5699   ID979          H_       GB             1       NaN   
5704   ID983          H_       US             1       NaN   
5709   ID988          H_       GB             1       NaN   
5711    ID99          H_       DE             5       joy   
5720   ID998          H_       GB             1       NaN   

                                          text_reviews_  \
0     Fast shipping! All cloths was finally fits wel...   
2     My order took 6 days with a snow day and a wee...   
3     Wouldnt give them no stars. I ordered a coat 4...   
4     Parcel never arrived. Cha

In [ ]:
#Semi-supervised learning for emotion prediction

In [ ]:
import pandas as pd
import numpy as np
import re

from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.semi_supervised import LabelSpreading
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
unlabeled_data = df[df['emotions_'].isna()][['lemmatized_text']]
unlabeled_data['emotions_'] = -1
print(unlabeled_data)

                                        lemmatized_text  emotions_
0                fast ship cloth final fit well satisfi         -1
4     parcel never arriv chase refund substanti amou...         -1
5     avoid order onlin order 12 day ago evri packag...         -1
6     aw servic return item book collect via evri tw...         -1
15    least confirm deliveri time state websit compl...         -1
...                                                 ...        ...
5693  order outfit child christma parti pay next day...         -1
5699  order onlin blame delay evri courier case let ...         -1
5704                    terribl return polici never buy         -1
5709  total mind blow aw custom servicesdo buy onlin...         -1
5720  complain late deliveri horrend compnay review ...         -1

[1165 rows x 2 columns]


In [ ]:
# Define labeled data as data where "emotions_" is not missing
labeled_data = df[df['emotions_'].notna() & (df['emotions_'] != 'NaN')]
# Extract labels from labeled_data
y_labeled = labeled_data['emotions_']
y_unlabeled = unlabeled_data['emotions_']
X_labeled = labeled_data['lemmatized_text']
X_unlabeled = unlabeled_data['lemmatized_text']

print("y_labeled ",y_labeled )
print("y_unlabeled",y_unlabeled)
print("X_unlabeled",X_unlabeled)
print("X_labeled",X_labeled)
print(df)

y_labeled  2           joy
3          fear
18        anger
25      neutral
52      sadness
         ...   
5607      anger
5646    sadness
5692    sadness
5695       fear
5711        joy
Name: emotions_, Length: 278, dtype: object
y_unlabeled 0      -1
4      -1
5      -1
6      -1
15     -1
       ..
5693   -1
5699   -1
5704   -1
5709   -1
5720   -1
Name: emotions_, Length: 1165, dtype: int64
X_unlabeled 0                  fast ship cloth final fit well satisfi
4       parcel never arriv chase refund substanti amou...
5       avoid order onlin order 12 day ago evri packag...
6       aw servic return item book collect via evri tw...
15      least confirm deliveri time state websit compl...
                              ...                        
5693    order outfit child christma parti pay next day...
5699    order onlin blame delay evri courier case let ...
5704                      terribl return polici never buy
5709    total mind blow aw custom servicesdo buy onlin...
5720    com

In [ ]:
# Parameters
sdg_params = dict(alpha=1e-5, penalty="l2", loss="log_loss")
vectorizer_params = dict(ngram_range=(1, 2), min_df=1, max_df=0.8)

# Supervised Pipeline
pipeline = Pipeline(
    [
        ("vect", CountVectorizer(**vectorizer_params)),
        ("tfidf", TfidfTransformer()),
        ("clf", SGDClassifier(**sdg_params)),
    ]
)

# LabelSpreading Pipeline
ls_pipeline = Pipeline(
    [
        ("vect", CountVectorizer(**vectorizer_params)),
        ("tfidf", TfidfTransformer()),
        ("toarray", FunctionTransformer(lambda x: x.toarray())),
        ("clf", LabelSpreading(kernel='rbf', gamma=20, n_neighbors=7, alpha=0.2, max_iter=30, tol=0.001, n_jobs=None)),
    ]
)

In [ ]:
def eval_and_print_metrics(clf, X_train, y_train, X_test, y_test):
    print("Number of training samples:", len(X_train))
    print("Unlabeled samples in training set:", sum(1 for x in y_train if x == -1)) #if x == 'NaN'
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)

    print(
        "Micro-averaged F1 score on test set: %0.3f"
        % f1_score(y_test, y_pred, average="micro")
    )
    print("\nConfusion Matrix:\n", confusion_matrix(y_test,y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred,zero_division=1))
    print("\n\n")

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_labeled, y_labeled, test_size=0.2, stratify=y_labeled, random_state=42)

In [ ]:
print("Supervised SGDClassifier on the labeled data:")
eval_and_print_metrics(pipeline, X_train, y_train, X_test, y_test)

Supervised SGDClassifier on the labeled data:
Number of training samples: 222
Unlabeled samples in training set: 0
Micro-averaged F1 score on test set: 0.500

Confusion Matrix:
 [[ 1  0  1  0  2  1  0]
 [ 1  2  0  0  2  0  0]
 [ 0  0  4  0  2  1  0]
 [ 0  1  1  8  1  1  0]
 [ 0  1  0  0 11  0  0]
 [ 1  0  2  1  3  2  0]
 [ 1  0  1  0  2  2  0]]

Classification Report:
               precision    recall  f1-score   support

       anger       0.25      0.20      0.22         5
     disgust       0.50      0.40      0.44         5
        fear       0.44      0.57      0.50         7
         joy       0.89      0.67      0.76        12
     neutral       0.48      0.92      0.63        12
     sadness       0.29      0.22      0.25         9
    surprise       1.00      0.00      0.00         6

    accuracy                           0.50        56
   macro avg       0.55      0.43      0.40        56
weighted avg       0.57      0.50      0.46        56






In [ ]:
print("Label Spreading on the labeled data:")
eval_and_print_metrics(ls_pipeline, X_train, y_train, X_test, y_test)

Label Spreading on the labeled data:
Number of training samples: 222
Unlabeled samples in training set: 0
Micro-averaged F1 score on test set: 0.429

Confusion Matrix:
 [[2 0 1 0 1 1 0]
 [3 0 0 0 1 1 0]
 [0 0 4 0 2 1 0]
 [0 0 1 9 1 1 0]
 [0 0 1 4 7 0 0]
 [1 1 1 1 3 2 0]
 [0 1 1 0 3 1 0]]

Classification Report:
               precision    recall  f1-score   support

       anger       0.33      0.40      0.36         5
     disgust       0.00      0.00      0.00         5
        fear       0.44      0.57      0.50         7
         joy       0.64      0.75      0.69        12
     neutral       0.39      0.58      0.47        12
     sadness       0.29      0.22      0.25         9
    surprise       1.00      0.00      0.00         6

    accuracy                           0.43        56
   macro avg       0.44      0.36      0.32        56
weighted avg       0.46      0.43      0.38        56






In [ ]:
test_indices = X_test.index

# Exclude test data from X_labeled and y_labeled based on the identified indices
X_labeled_filtered = X_labeled.drop(index=test_indices, errors='ignore')
y_labeled_filtered = y_labeled.drop(index=test_indices, errors='ignore')

# Concatenate the filtered labeled data with the unlabeled data
X=X_combined = pd.concat([X_labeled_filtered, X_unlabeled])
y=y_combined = pd.concat([y_labeled_filtered, y_unlabeled])

In [ ]:
# Define the mapping for labels
label_mapping = {'anger': 1, 'disgust': 2, 'fear': 3, 'joy': 4, 'neutral': 5, 'sadness': 6, "surprise": 7,-1:-1 }

# Apply the mapping to labels
y  = [label_mapping[label] for label in y]
y_test  = [label_mapping[label] for label in y_test]


In [ ]:
print("Label  Classifier on the labeled and unlabeled data:")
eval_and_print_metrics(ls_pipeline, X, y, X_test, y_test)

Label  Classifier on the labeled and unlabeled data:
Number of training samples: 1387
Unlabeled samples in training set: 1165
Micro-averaged F1 score on test set: 0.429

Confusion Matrix:
 [[2 0 1 0 2 0 0]
 [0 0 0 1 2 2 0]
 [0 0 4 0 3 0 0]
 [0 0 0 8 2 2 0]
 [0 1 1 2 7 1 0]
 [1 0 2 0 3 3 0]
 [0 0 0 1 5 0 0]]

Classification Report:
               precision    recall  f1-score   support

           1       0.67      0.40      0.50         5
           2       0.00      0.00      0.00         5
           3       0.50      0.57      0.53         7
           4       0.67      0.67      0.67        12
           5       0.29      0.58      0.39        12
           6       0.38      0.33      0.35         9
           7       1.00      0.00      0.00         6

    accuracy                           0.43        56
   macro avg       0.50      0.36      0.35        56
weighted avg       0.49      0.43      0.39        56






In [ ]:
print(df)

         ID_ brand_name_ country_  star_rating_ emotions_  \
0        ID1          Z_       US             5       NaN   
2      ID100          H_      FRI             5       joy   
3     ID1000          H_       GB             1      fear   
4     ID1001          H_       GB             1       NaN   
5     ID1002          H_       GB             1       NaN   
...      ...         ...      ...           ...       ...   
5699   ID979          H_       GB             1       NaN   
5704   ID983          H_       US             1       NaN   
5709   ID988          H_       GB             1       NaN   
5711    ID99          H_       DE             5       joy   
5720   ID998          H_       GB             1       NaN   

                                          text_reviews_  \
0     Fast shipping! All cloths was finally fits wel...   
2     My order took 6 days with a snow day and a wee...   
3     Wouldnt give them no stars. I ordered a coat 4...   
4     Parcel never arrived. Cha

In [ ]:
#Imputing predicted emotions
predicted_emotions = ls_pipeline.predict(X_unlabeled)
print(predicted_emotions)

[5 5 3 ... 3 5 5]


In [ ]:
# Add predicted labels to the unlabeled data DataFrame
unlabeled_data['emotions_'] = predicted_emotions

In [ ]:
combined_data = pd.concat([labeled_data, unlabeled_data])
print(combined_data)

         ID_ brand_name_ country_  star_rating_ emotions_  \
2      ID100          H_      FRI           5.0       joy   
3     ID1000          H_       GB           1.0      fear   
18    ID1014          H_       GB           1.0     anger   
25    ID1020          H_       GB           1.0   neutral   
52    ID1045          H_       GB           1.0   sadness   
...      ...         ...      ...           ...       ...   
5693     NaN         NaN      NaN           NaN         3   
5699     NaN         NaN      NaN           NaN         5   
5704     NaN         NaN      NaN           NaN         3   
5709     NaN         NaN      NaN           NaN         5   
5720     NaN         NaN      NaN           NaN         5   

                                          text_reviews_  \
2     My order took 6 days with a snow day and a wee...   
3     Wouldnt give them no stars. I ordered a coat 4...   
18    Trying to order a product online but if I do i...   
25                 Only because

In [ ]:
# Replace the 'emotions_' column in the original DataFrame
df['emotions_'] = combined_data['emotions_']

In [ ]:
# Check for any remaining NaNs in 'emotions_'
print(df['emotions_'].isna().sum())

print(df.head())


0
      ID_ brand_name_ country_  star_rating_  emotions_  \
0     ID1          Z_       US             5          5   
2   ID100          H_      FRI             5          4   
3  ID1000          H_       GB             1          3   
4  ID1001          H_       GB             1          5   
5  ID1002          H_       GB             1          3   

                                       text_reviews_  \
0  Fast shipping! All cloths was finally fits wel...   
2  My order took 6 days with a snow day and a wee...   
3  Wouldnt give them no stars. I ordered a coat 4...   
4  Parcel never arrived. Chasing for a refund for...   
5  Avoid ordering online! Ordered 12 days ago, Ev...   

                                     cleaned_reviews  \
0  fast shipping all cloths was finally fits well...   
2  my order took 6 days with a snow day and a wee...   
3  wouldnt give them no stars i ordered a coat 4 ...   
4  parcel never arrived chasing for a refund for ...   
5  avoid ordering online o

In [ ]:
#Changing the original labels in emotions_ to numeric mapping

emotion_mapping = {
    'anger': 1,
    'disgust': 2,
    'fear': 3,
    'joy': 4,
    'neutral': 5,
    'sadness': 6,
    'surprise': 7
}
df['emotions_'] = df['emotions_'].replace(emotion_mapping)

print(df)

         ID_ brand_name_ country_  star_rating_  emotions_  \
0        ID1          Z_       US             5          5   
2      ID100          H_      FRI             5          4   
3     ID1000          H_       GB             1          3   
4     ID1001          H_       GB             1          5   
5     ID1002          H_       GB             1          3   
...      ...         ...      ...           ...        ...   
5699   ID979          H_       GB             1          5   
5704   ID983          H_       US             1          3   
5709   ID988          H_       GB             1          5   
5711    ID99          H_       DE             5          4   
5720   ID998          H_       GB             1          5   

                                          text_reviews_  \
0     Fast shipping! All cloths was finally fits wel...   
2     My order took 6 days with a snow day and a wee...   
3     Wouldnt give them no stars. I ordered a coat 4...   
4     Parcel never 

In [ ]:
#Supervised Machine Learning to predict sentiment

X_train2, X_test2, y_train2, y_test2 = train_test_split(df['lemmatized_text'], df['Sentiment'], test_size=0.2, random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train2)
X_test_tfidf = tfidf_vectorizer.transform(X_test2)

In [ ]:
#SUPERVISED LEARNING NOT COMPLETE, AFTER YOU DO LIT REVIEW, FIGURE OUT BEST ALGORITHM FOR SENTIMENT PREDICTION, THEN JUST REFER LAB7D

In [ ]:
#VIZ FOR INSIGHTS ETC.